$("#xsnazzy").corner();
$(".xsnazzy").corner();
$("#news1").corner();
$("#news2").corner();
$(".playerbox").corner();


animatedcollapse.addDiv('teamtotals', 'fade=1');
animatedcollapse.addDiv('totalsalaries', 'fade=1');
animatedcollapse.addDiv('totalpoints', 'fade=1');
animatedcollapse.addDiv('total3pointers', 'fade=1');
animatedcollapse.addDiv('totalsteals', 'fade=1');
animatedcollapse.addDiv('totalrebounds', 'fade=1');
animatedcollapse.addDiv('totalfreethrows', 'fade=1');
animatedcollapse.addDiv('totalblocks', 'fade=1');
animatedcollapse.addDiv('totalassists', 'fade=1');
animatedcollapse.init();
