
animatedcollapse.addDiv('teamtotals', 'fade=1,height=310px');
animatedcollapse.addDiv('totalsalaries', 'fade=1,height=310px');
animatedcollapse.addDiv('totalpoints', 'fade=1,height=370px');
animatedcollapse.addDiv('total3pointers', 'fade=1,height=390px');
animatedcollapse.addDiv('totalsteals', 'fade=1,height=370px');
animatedcollapse.addDiv('totalrebounds', 'fade=1,height=370px');
animatedcollapse.addDiv('totalfreethrows', 'fade=1,height=380px');
animatedcollapse.addDiv('totalblocks', 'fade=1,height=370px');
animatedcollapse.addDiv('totalassists', 'fade=1,height=370px');
animatedcollapse.init();